In [27]:
import pandas as pd
from glob import iglob

In [4]:
clinical = pd.read_csv('../data/Demo_data.csv')

clinical

,Patient ID,sex,Age,Height,Weight,BMI,waist,Fasting Blood sugar,Cre,Urea,...,Ferritin,Insulin,CRP,Vitamin A,OH,Steatosis stage,CAP score,E score,Fibroscan S,Fibroscan F
0,TAL01331,M,34,186,96.0,27.7,102.0,102,1.00,30,...,131.51,19.55,2.2,57.0,25.0,3,310.0,5.3,3,1
1,TAL02130,M,48,173,88.0,29.0,103.0,104,1.00,30,...,158.00,10.00,1.0,29.0,25.0,1,289.0,3.6,3,0
2,TAL03101,M,52,173,88.0,29.0,103.0,99,1.14,38,...,271.00,10.00,2.0,29.0,25.0,1,237.0,4.5,0,1
3,TAL04102,F,68,173,88.0,29.0,103.0,98,1.00,30,...,158.00,10.00,1.0,29.0,25.0,1,240.0,9.0,0,2
4,TAL05211,F,68,173,88.0,29.0,103.0,100,1.00,30,...,158.00,10.00,2.0,29.0,25.0,2,260.0,6.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108,BEH92111,M,42,173,88.0,29.0,103.0,85,1.11,35,...,158.00,10.00,1.0,29.0,13.0,1,NaN,NaN,1,1
109,BEH93231,M,37,173,88.0,29.0,103.0,93,1.02,31,...,158.00,10.00,1.0,29.0,25.0,2,288.0,4.4,3,1
110,BEH94131,M,48,178,121.3,38.3,126.6,148,1.04,33,...,158.00,10.00,1.0,29.0,25.0,1,343.0,6.6,3,1
111,BEH95110,M,52,167,72.0,25.8,82.7,92,1.25,42,...,158.00,10.00,1.0,29.0,26.0,1,248.0,3.7,1,0
112,BEH96100,M,40,169,76.5,26.8,93.9,88,0.91,31,...,158.00,10.00,1.0,29.0,11.0,1,226.0,3.2,0,0

In [12]:
clinical.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,113.0,44.026549,7.851820,21.00,42.00,44.00,48.00,69.00
Height,113.0,172.991150,4.298039,155.00,173.00,173.00,173.00,186.00
Weight,113.0,88.123894,9.837122,53.00,88.00,88.00,88.00,134.60
BMI,113.0,29.114159,2.523315,22.10,29.00,29.00,29.00,40.20
waist,113.0,103.025664,8.548859,74.00,103.00,103.00,103.00,141.70
Fasting Blood sugar,113.0,97.646018,18.146684,70.00,89.00,97.00,99.00,194.00
Cre,113.0,0.999646,0.109878,0.74,0.95,1.00,1.04,1.30
Urea,113.0,30.132743,4.359932,18.00,28.00,30.00,32.00,42.00
Uric Acid,113.0,6.068142,1.073734,3.10,5.50,6.00,6.60,9.00
Triglyceride,113.0,197.008850,161.154456,50.00,119.00,186.00,200.00,1400.00
Cholestrol,113.0,182.840708,33.674536,86.00,165.00,183.00,200.00,310.00
HDL,113.0,42.017699,6.138262,30.00,40.00,41.00,43.00,73.00
LDL,113.0,117.902655,128.739768,29.00,93.00,110.00,118.00,1442.00
LDL/HDL,113.0,2.322743,0.612446,0.70,2.00,2.00,2.70,4.10
Iron,113.0,8.053097,12.215798,0.50,8.00,8.00,8.00,99.00
TIBC,113.0,15.971947,36.273568,0.11,16.00,16.00,16.00,392.00
Bilirubin total,113.0,9.906726,11.845346,0.30,0.80,2.20,18.00,55.00
Bilirubin Direct,113.0,10.295310,13.780840,0.08,0.20,0.40,16.00,50.00
GGT,113.0,34.964602,14.869029,10.00,35.00,35.00,35.00,162.00
Albumin,113.0,3.992035,0.190461,3.20,4.00,4.00,4.00,5.00
AST (SGOT),113.0,73.734513,72.588003,15.00,24.00,37.00,74.00,328.00
ALT (SGPT),113.0,117.864602,538.325670,7.70,26.00,45.00,118.00,5770.00
Alkaline Phosphatase,113.0,316.950442,782.467876,14.40,174.00,281.00,317.00,8520.00
HbA1c,113.0,7.013540,0.898988,5.13,7.00,7.00,7.00,15.60
WBC,113.0,6891.975398,1722.234003,5.52,6110.00,6892.00,7540.00,12080.00
Hemoglobin,113.0,16.353982,7.190706,12.50,15.00,16.00,16.00,85.10
RBC,113.0,6.726814,7.535474,4.31,5.19,5.61,7.00,82.50
Hematocrit,113.0,45.212389,3.385661,28.30,44.40,45.00,47.10,51.90
MCV,113.0,86.000885,13.802235,34.30,82.90,86.00,86.80,215.00
MCH,113.0,31.828319,25.266722,20.60,27.80,29.70,32.00,297.00
MCHC,113.0,33.233628,1.062058,27.80,33.00,33.00,33.70,35.70
Platelets,113.0,239.106195,46.192022,125.00,211.00,239.00,261.00,403.00
Neutrophil,113.0,20.010531,3.767958,2.57,20.00,20.00,20.00,52.90
Lymphocyte,113.0,15.005664,3.042428,1.85,15.00,15.00,15.00,41.50
Monocyte,113.0,0.006460,0.049658,0.00,0.00,0.00,0.00,0.45
Eosinophil,113.0,0.006903,0.065385,0.00,0.00,0.00,0.00,0.69
basophil,113.0,0.000885,0.007141,0.00,0.00,0.00,0.00,0.07
Neutrophil%,113.0,58.011504,0.612919,53.30,58.00,58.00,58.00,62.00
Lymphocyte%,113.0,31.009735,0.904943,24.80,31.00,31.00,31.00,38.30
Monocyte%,113.0,5.012389,0.101886,4.90,5.00,5.00,5.00,5.90
Eosinophil%,113.0,4.994690,0.376269,1.90,5.00,5.00,5.00,7.50
Basophil%,113.0,0.994690,0.041920,0.60,1.00,1.00,1.00,1.00
Patient PT,113.0,13.003540,0.188476,12.00,13.00,13.00,13.00,14.70
Control PT,113.0,12.991150,0.115386,12.00,13.00,13.00,13.00,13.50
Activity%,113.0,93.991150,0.871120,87.00,94.00,94.00,94.00,100.00
INR,113.0,1.001062,0.008901,1.00,1.00,1.00,1.00,1.09
ESR,113.0,7.000000,0.000000,7.00,7.00,7.00,7.00,7.00
T3,113.0,50.016991,9.518705,0.83,50.00,50.00,50.00,113.00
T4,113.0,27.011504,7.504805,1.20,27.00,27.00,27.00,96.00
TSH,113.0,21.981770,8.285992,1.00,22.00,22.00,22.00,100.00
Ferritin,113.0,158.030177,17.214007,84.60,158.00,158.00,158.00,271.00
Insulin,113.0,10.011947,1.067734,4.70,10.00,10.00,10.00,19.55
CRP,113.0,1.040708,0.206863,0.90,1.00,1.00,1.00,2.20
Vitamin A,113.0,28.996991,3.764442,0.66,29.00,29.00,29.00,57.00
OH,113.0,24.914159,8.230419,5.00,22.00,25.00,25.00,52.00
Steatosis stage,113.0,1.353982,0.766723,0.00,1.00,1.00,2.00,3.00
CAP score,94.0,282.000000,43.284754,144.00,256.00,287.50,309.75,370.00
E score,96.0,5.114167,1.352875,3.10,4.20,4.70,6.10,9.60
Fibroscan S,113.0,1.991150,1.145609,0.00,1.00,2.00,3.00,3.00
Fibroscan F,113.0,0.884956,0.546943,0.00,1.00,1.00,1.00,2.00

In [16]:
clinical.info()

<class 'pandas.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 62 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Patient ID            113 non-null    str
 1   sex                   113 non-null    str
 2   Age                   113 non-null    int64
 3   Height                113 non-null    int64
 4   Weight                113 non-null    float64
 5   BMI                   113 non-null    float64
 6   waist                 113 non-null    float64
 7   Fasting Blood sugar   113 non-null    int64
 8   Cre                   113 non-null    float64
 9   Urea                  113 non-null    int64
 10  Uric Acid             113 non-null    float64
 11  Triglyceride          113 non-null    int64
 12  Cholestrol            113 non-null    int64
 13  HDL                   113 non-null    int64
 14  LDL                   113 non-null    int64
 15  LDL/HDL               113 non-null    float64
 16  Iron                  113 non-null    float64
 17  TIBC                  113 non-null    float64
 18  Bilirubin total       113 non-null    float64
 19  Bilirubin Direct      113 non-null    float64
 20  GGT                   113 non-null    int64
 21  Albumin               113 non-null    float64
 22  AST (SGOT)            113 non-null    int64
 23  ALT (SGPT)            113 non-null    float64
 24  Alkaline Phosphatase  113 non-null    float64
 25  HbA1c                 113 non-null    float64
 26  WBC                   113 non-null    float64
 27  Hemoglobin            113 non-null    float64
 28  RBC                   113 non-null    float64
 29  Hematocrit            113 non-null    float64
 30  MCV                   113 non-null    float64
 31  MCH                   113 non-null    float64
 32  MCHC                  113 non-null    float64
 33  Platelets             113 non-null    int64
 34  Neutrophil            113 non-null    float64
 35  Lymphocyte            113 non-null    float64
 36  Monocyte              113 non-null    float64
 37  Eosinophil            113 non-null    float64
 38  basophil              113 non-null    float64
 39  Neutrophil%           113 non-null    float64
 40  Lymphocyte%           113 non-null    float64
 41  Monocyte%             113 non-null    float64
 42  Eosinophil%           113 non-null    float64
 43  Basophil%             113 non-null    float64
 44  Patient PT            113 non-null    float64
 45  Control PT            113 non-null    float64
 46  Activity%             113 non-null    int64
 47  INR                   113 non-null    float64
 48  ESR                   113 non-null    int64
 49  T3                    113 non-null    float64
 50  T4                    113 non-null    float64
 51  TSH                   113 non-null    float64
 52  Ferritin              113 non-null    float64
 53  Insulin               113 non-null    float64
 54  CRP                   113 non-null    float64
 55  Vitamin A             113 non-null    float64
 56  OH                    113 non-null    float64
 57  Steatosis stage       113 non-null    int64
 58  CAP score             94 non-null     float64
 59  E score               96 non-null     float64
 60  Fibroscan S           113 non-null    int64
 61  Fibroscan F           113 non-null    int64
dtypes: float64(44), int64(16), str(2)
memory usage: 54.9 KB

In [ ]:
imageMap = pd.read_csv('../data/BEHSOF_images.csv')

imageMap

         Patient ID  Steatosis stage  Fibroscan F
0    \Data\TAL01331                3            1
1    \Data\TAL02130                1            0
2    \Data\TAL03101                1            1
3    \Data\TAL04102                1            2
4    \Data\TAL05211                2            1
..              ...              ...          ...
108  \Data\BEH92111                1            1
109  \Data\BEH93231                2            1
110  \Data\BEH94131                1            1
111  \Data\BEH95110                1            0
112  \Data\BEH96100                1            0

[113 rows x 3 columns]

In [14]:
imageMap.info()

<class 'pandas.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Patient ID       113 non-null    str
 1   Steatosis stage  113 non-null    int64
 2   Fibroscan F      113 non-null    int64
dtypes: int64(2), str(1)
memory usage: 2.8 KB

In [17]:
imageMap.nunique()

Patient ID         113
Steatosis stage      4
Fibroscan F          3
dtype: int64

In [37]:
# Check image directories map with patient ID

patientID = imageMap['Patient ID']

patientID = patientID.str.replace('\\Data\\', '', regex = False)

patientID = set(patientID)

imageDataDirs = set(d.replace('../data/image_Data/', '') for d in iglob('../data/image_Data/*'))

if patientID == imageDataDirs:
    print('PatientID maps to a directory in image_Data')
else:
    print('PatientId does not match directories in image_Data')

PatientID maps to a directory in image_Data

In [ ]:
# TODO: check number of images per patient, number per hosptical/clinic, distribution of clinical values and/or correlations